# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IloweTest < Formula
  desc ""
  homepage ""
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iainlowe/ilowe-test/releases/download/v0.4.0/ilowe-test_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "36279b7d942b30e378206951ccb5d707fa3b0f928c3272424c8127f8bbeb300e"

      def install
        bin.install "ilowe-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iainlowe/ilowe-test/releases/download/v0.4.0/ilowe-test_0.4.0_Darwin_arm64.tar.gz"
      sha256 "d1dc8073221fcfaf039a2bbb6650843ab54ee9f28453f879cf407b3e345fd442"

      def install
        bin.install "ilowe-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/iainlowe/ilowe-test/releases/download/v0.4.0/ilowe-test_0.4.0_Linux_x86_64.tar.gz"
      sha256 "d3bceaa94d33a1784f3c245b03623fa132efe356b6631f569409d418e86d44d7"

      def install
        bin.install "ilowe-test"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iainlowe/ilowe-test/releases/download/v0.4.0/ilowe-test_0.4.0_Linux_arm64.tar.gz"
      sha256 "7f9da69c67e42ca043e0c542f0596fce3980882731401cbfe112b13c6b31f45a"

      def install
        bin.install "ilowe-test"
      end
    end
  end

  def caveats; <<~EOS
    Be careful, this is just a test!
  EOS
  end
end
