# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IloweTest < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iainlowe/ilowe-test/releases/download/v0.1.1/ilowe-test_0.1.1_Darwin_arm64.tar.gz"
      sha256 "9e6237cfccc01a401f5e3b728afe7379d744cb035064170c38fd24adafcd92e8"

      def install
        bin.install "ilowe-test"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iainlowe/ilowe-test/releases/download/v0.1.1/ilowe-test_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "4e8d76552f7fa1cdd8665aab5541fba102c8fecfd1219b8ef665d055ab4e13dc"

      def install
        bin.install "ilowe-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iainlowe/ilowe-test/releases/download/v0.1.1/ilowe-test_0.1.1_Linux_arm64.tar.gz"
      sha256 "e9aed16affffd07de58c0adc0c409eb0a2633f0107f7d09fdb3a98f7976cbce4"

      def install
        bin.install "ilowe-test"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iainlowe/ilowe-test/releases/download/v0.1.1/ilowe-test_0.1.1_Linux_x86_64.tar.gz"
      sha256 "33e42ab3c23a9149259e7408b4980753573e046fe1afa64682c5d3757590f943"

      def install
        bin.install "ilowe-test"
      end
    end
  end

  def caveats; <<~EOS
    Be careful, this is just a test!
  EOS
  end
end
